version: '3.7'

services:

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'dyescape-bot'
      MYSQL_USER: 'dyescape'
      MYSQL_PASSWORD: 'bot'
      MYSQL_ROOT_PASSWORD: 'dyescape-bot'
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
